services:
  db:
      image: mysql
      ports: 
          - "3306:3306"
      command: --default-authentication-plugin=mysql_native_password
      environment:
          MYSQL_DATABASE: erp
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test 
      volumes:
          - ./db:/var/lib/mysql
          - my-db:/var/lib/mysql
  api:
    image: robertcharca/api_testing:latest        
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
volumes:
    my-db:
